{{- if .Values.simulator.exampleCertificate.enabled  }}


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:

  name: {{ .Values.simulator.exampleCertificate.name | default "adcs-sim-certificate" }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: example.com
  dnsNames:
  - adcs1.example.com
  - adcs2.example.com

  issuerRef:
    group: adcs.certmanager.csf.nokia.com
    kind: ClusterAdcsIssuer
    name: {{ .Values.simulator.clusterIssuserName | default "adcs-sim-adcsclusterissuer" }}

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Your organization

  secretName: {{.Values.simulator.secretName | default "adcs-sim-secret" }} 


{{- end  }}    