name: Publish ADCS Simulator Docker image on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get the version from tag
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/tags/}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          COMMIT: 'variableContent'
          BUILD_TIME: 'variableContent'  
          PROJECT: 'github.com/nokia/adcs-sim/adcs-sim'
          #COMMIT?=$(shell git rev-parse --short HEAD)
          #BUILD_TIME?=$(shell date -u '+%Y-%m-%d_%H:%M:%S')
          #PROJECT?=github.com/nokia/adcs-sim/adcs-sim


      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          name: djkormo/adcs-sim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: VERSION,COMMIT,BUILD_TIME,PROJECT
          tags: "latest,${{ env.VERSION }}"
          dockerfile: ./test/Dockerfile

